version: "3.9"
    
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_pref
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    
  donor-store:
    depends_on:
      - db
    image: donor-store
    ports:
      - "8080:8080"
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: db_user
      DB_PASSWORD: password
      DB_NAME: users_pref
  
  donor-store-gui:
    depends_on:
      - donor-store
    image: donor-store-gui
    ports:
      - "8081:8081"
    restart: always
volumes:
  db_data: {}

networks:
  donor-network :