version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_pref
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    
  server:
    depends_on:
      - db
    image: busybox
    ports:
      - "8000:80"
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: db_user
      DB_PASSWORD: password
      DB_NAME: users_pref
volumes:
  db_data: {}